version: '3'

services:
  spark_etl_template:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app/:/app/app/
      - ./tests/:/app/tests/
      - ./main.py:/app/main.py
    command: tail -f /dev/null